spring:
  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: ${MICROSOFT_CLIENT_ID}
            client-secret: ${MICROSOFT_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - offline_access
              - Mail.ReadWrite
              - Mail.Read
              - User.Read
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/microsoft"
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
            user-name-attribute: sub
  application:
    name: recruitment-automation

aws:
  s3:
    region: ap-south-1
    bucket: caizin-recruitment-resumes
    base-folder: resumes

# OpenAI (key from environment; do not commit)
openai:
  api-key: ${OPENAI_API_KEY:}
# Google Apps Script Web App URL (deploy as Web App, execute as me, who has access: anyone)
google:
  apps:
    script:
      url: ${GOOGLE_APPS_SCRIPT_URL:}